<a href="https://colab.research.google.com/github/Bishre313/testing/blob/main/AETS1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor

In [ ]:
df = pd.read_excel('/content/combined_10files_2000rows.xlsx')
df.head()

,DayNum,VehId,Trip,Timestamp(ms),Latitude[deg],Longitude[deg],Vehicle Speed[km/h],MAF[g/sec],Engine RPM[RPM],Absolute Load[%],...,Energy_Consumption,Matchted Latitude[deg],Matched Longitude[deg],Match Type,Class of Speed Limit,Speed Limit[km/h],Speed Limit with Direction[km/h],Intersection,Bus Stops,Focus Points
0,57.05024,139,1163,0,42.302634,-83.704336,16.0,20.770000,1934.0,56.470589,...,0.001968,42.302591,-83.704333,0,0.0,72,72.0,NaN,NaN,NaN
1,57.05024,139,1163,900,42.302634,-83.704336,23.0,18.240000,1776.0,56.470589,...,0.002485,42.302591,-83.704333,1,0.0,72,72.0,NaN,NaN,NaN
2,57.05024,139,1163,1900,42.302634,-83.704336,29.0,18.240000,1776.0,56.470589,...,0.003133,42.302591,-83.704333,1,0.0,72,72.0,NaN,NaN,NaN
3,57.05024,139,1163,2900,42.302634,-83.704336,32.0,20.809999,1772.0,56.470589,...,0.003944,42.302591,-83.704333,1,0.0,72,72.0,NaN,NaN,NaN
4,57.05024,139,1163,3000,42.302610,-83.704049,32.0,20.809999,1772.0,56.470589,...,0.003944,42.302600,-83.704049,0,0.0,72,72.0,NaN,NaN,NaN

EDA

In [ ]:
df.describe()

,DayNum,VehId,Trip,Timestamp(ms),Latitude[deg],Longitude[deg],Vehicle Speed[km/h],MAF[g/sec],Engine RPM[RPM],Absolute Load[%],...,Elevation Smoothed[m],Gradient,Energy_Consumption,Matchted Latitude[deg],Matched Longitude[deg],Match Type,Class of Speed Limit,Speed Limit with Direction[km/h],Intersection,Bus Stops
count,20000.000000,20000.000000,20000.000000,2.000000e+04,20000.000000,20000.000000,20000.000000,13396.000000,13602.000000,10123.000000,...,20000.000000,19556.000000,19291.000000,20000.000000,20000.000000,20000.000000,19638.000000,19638.000000,844.0,417.0
mean,259.957227,66.853600,1952.971800,3.334448e+05,42.281327,-83.726518,36.031016,10.619685,1323.041906,33.312298,...,258.300537,0.000030,0.002735,42.281322,-83.726526,0.838250,0.289184,54.360322,1.0,1.0
std,94.334087,80.661242,980.905981,3.283773e+05,0.017782,0.024883,24.470641,9.163357,644.334186,17.787162,...,15.116814,0.002911,0.003856,0.017785,0.024887,0.375891,0.467333,14.352963,0.0,0.0
min,57.030665,10.000000,708.000000,0.000000e+00,42.223653,-83.801672,0.000000,0.450000,0.000000,0.000000,...,227.514908,-0.067265,-0.009607,42.223671,-83.801672,0.000000,-1.000000,16.000000,1.0,1.0
25%,246.760230,10.000000,922.000000,8.210000e+04,42.276369,-83.743956,16.000000,4.170000,875.000000,19.215687,...,247.058176,0.000000,0.000217,42.276322,-83.743911,1.000000,0.000000,40.000000,1.0,1.0
50%,292.236635,12.000000,1778.000000,2.072000e+05,42.283264,-83.730451,37.000000,6.380000,1394.000000,29.803923,...,256.901016,0.000000,0.001625,42.283257,-83.730449,1.000000,0.000000,56.000000,1.0,1.0
75%,309.588456,140.000000,2949.000000,4.993000e+05,42.290365,-83.707480,54.192498,15.850000,1725.000000,46.666668,...,270.086707,0.000000,0.004367,42.290382,-83.707474,1.000000,1.000000,56.000000,1.0,1.0
max,372.882455,235.000000,4144.000000,1.389800e+06,42.321784,-83.674106,131.000000,71.169998,3524.000000,131.372559,...,293.813232,0.063695,0.037033,42.321876,-83.674117,2.000000,2.000000,113.000000,1.0,1.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 35 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   DayNum                            20000 non-null  float64
 1   VehId                             20000 non-null  int64
 2   Trip                              20000 non-null  int64
 3   Timestamp(ms)                     20000 non-null  int64
 4   Latitude[deg]                     20000 non-null  float64
 5   Longitude[deg]                    20000 non-null  float64
 6   Vehicle Speed[km/h]               20000 non-null  float64
 7   MAF[g/sec]                        13396 non-null  float64
 8   Engine RPM[RPM]                   13602 non-null  float64
 9   Absolute Load[%]                  10123 non-null  float64
 10  OAT[DegC]                         8447 non-null   float64
 11  Fuel Rate[L/hr]                   0 non-null      float64
 12  Air Conditioning Power[kW]        0 non-null      float64
 13  Air Conditioning Power[Watts]     7290 non-null   float64
 14  Heater Power[Watts]               6398 non-null   float64
 15  HV Battery Current[A]             7290 non-null   float64
 16  HV Battery SOC[%]                 7290 non-null   float64
 17  HV Battery Voltage[V]             7290 non-null   float64
 18  Short Term Fuel Trim Bank 1[%]    13152 non-null  float64
 19  Short Term Fuel Trim Bank 2[%]    3073 non-null   float64
 20  Long Term Fuel Trim Bank 1[%]     12207 non-null  float64
 21  Long Term Fuel Trim Bank 2[%]     2128 non-null   float64
 22  Elevation Raw[m]                  20000 non-null  float64
 23  Elevation Smoothed[m]             20000 non-null  float64
 24  Gradient                          19556 non-null  float64
 25  Energy_Consumption                19291 non-null  float64
 26  Matchted Latitude[deg]            20000 non-null  float64
 27  Matched Longitude[deg]            20000 non-null  float64
 28  Match Type                        20000 non-null  int64
 29  Class of Speed Limit              19638 non-null  float64
 30  Speed Limit[km/h]                 19638 non-null  object
 31  Speed Limit with Direction[km/h]  19638 non-null  float64
 32  Intersection                      844 non-null    float64
 33  Bus Stops                         417 non-null    float64
 34  Focus Points                      568 non-null    object
dtypes: float64(29), int64(4), object(2)
memory usage: 5.3+ MB

In [ ]:
df.shape

(20000, 35)

In [ ]:
df.isnull().sum().sort_values(ascending=False)

Air Conditioning Power[kW]          20000
Fuel Rate[L/hr]                     20000
Bus Stops                           19583
Focus Points                        19432
Intersection                        19156
Long Term Fuel Trim Bank 2[%]       17872
Short Term Fuel Trim Bank 2[%]      16927
Heater Power[Watts]                 13602
HV Battery SOC[%]                   12710
HV Battery Current[A]               12710
HV Battery Voltage[V]               12710
Air Conditioning Power[Watts]       12710
OAT[DegC]                           11553
Absolute Load[%]                     9877
Long Term Fuel Trim Bank 1[%]        7793
Short Term Fuel Trim Bank 1[%]       6848
MAF[g/sec]                           6604
Engine RPM[RPM]                      6398
Energy_Consumption                    709
Gradient                              444
Class of Speed Limit                  362
Speed Limit[km/h]                     362
Speed Limit with Direction[km/h]      362
Trip                                    0
VehId                                   0
DayNum                                  0
Timestamp(ms)                           0
Vehicle Speed[km/h]                     0
Longitude[deg]                          0
Latitude[deg]                           0
Elevation Raw[m]                        0
Matchted Latitude[deg]                  0
Elevation Smoothed[m]                   0
Matched Longitude[deg]                  0
Match Type                              0
dtype: int64

In [ ]:
df.describe()

,DayNum,VehId,Trip,Timestamp(ms),Latitude[deg],Longitude[deg],Vehicle Speed[km/h],MAF[g/sec],Engine RPM[RPM],Absolute Load[%],...,Elevation Smoothed[m],Gradient,Energy_Consumption,Matchted Latitude[deg],Matched Longitude[deg],Match Type,Class of Speed Limit,Speed Limit with Direction[km/h],Intersection,Bus Stops
count,20000.000000,20000.000000,20000.000000,2.000000e+04,20000.000000,20000.000000,20000.000000,13396.000000,13602.000000,10123.000000,...,20000.000000,19556.000000,19291.000000,20000.000000,20000.000000,20000.000000,19638.000000,19638.000000,844.0,417.0
mean,259.957227,66.853600,1952.971800,3.334448e+05,42.281327,-83.726518,36.031016,10.619685,1323.041906,33.312298,...,258.300537,0.000030,0.002735,42.281322,-83.726526,0.838250,0.289184,54.360322,1.0,1.0
std,94.334087,80.661242,980.905981,3.283773e+05,0.017782,0.024883,24.470641,9.163357,644.334186,17.787162,...,15.116814,0.002911,0.003856,0.017785,0.024887,0.375891,0.467333,14.352963,0.0,0.0
min,57.030665,10.000000,708.000000,0.000000e+00,42.223653,-83.801672,0.000000,0.450000,0.000000,0.000000,...,227.514908,-0.067265,-0.009607,42.223671,-83.801672,0.000000,-1.000000,16.000000,1.0,1.0
25%,246.760230,10.000000,922.000000,8.210000e+04,42.276369,-83.743956,16.000000,4.170000,875.000000,19.215687,...,247.058176,0.000000,0.000217,42.276322,-83.743911,1.000000,0.000000,40.000000,1.0,1.0
50%,292.236635,12.000000,1778.000000,2.072000e+05,42.283264,-83.730451,37.000000,6.380000,1394.000000,29.803923,...,256.901016,0.000000,0.001625,42.283257,-83.730449,1.000000,0.000000,56.000000,1.0,1.0
75%,309.588456,140.000000,2949.000000,4.993000e+05,42.290365,-83.707480,54.192498,15.850000,1725.000000,46.666668,...,270.086707,0.000000,0.004367,42.290382,-83.707474,1.000000,1.000000,56.000000,1.0,1.0
max,372.882455,235.000000,4144.000000,1.389800e+06,42.321784,-83.674106,131.000000,71.169998,3524.000000,131.372559,...,293.813232,0.063695,0.037033,42.321876,-83.674117,2.000000,2.000000,113.000000,1.0,1.0

In [ ]:
for col in df.columns:
    print(repr(col))

'DayNum'
'VehId'
'Trip'
'Timestamp(ms)'
'Latitude[deg]'
'Longitude[deg]'
'Vehicle Speed[km/h]'
'MAF[g/sec]'
'Engine RPM[RPM]'
'Absolute Load[%]'
'OAT[DegC]'
'Fuel Rate[L/hr]'
'Air Conditioning Power[kW]'
'Air Conditioning Power[Watts]'
'Heater Power[Watts]'
'HV Battery Current[A]'
'HV Battery SOC[%]'
'HV Battery Voltage[V]'
'Short Term Fuel Trim Bank 1[%]'
'Short Term Fuel Trim Bank 2[%]'
'Long Term Fuel Trim Bank 1[%]'
'Long Term Fuel Trim Bank 2[%]'
'Elevation Raw[m]'
'Elevation Smoothed[m]'
'Gradient'
'Energy_Consumption'
'Matchted Latitude[deg]'
'Matched Longitude[deg]'
'Match Type'
'Class of Speed Limit'
'Speed Limit[km/h]'
'Speed Limit with Direction[km/h]'
'Intersection'
'Bus Stops'
'Focus Points'

In [ ]:
# Convert only the problematic column to numeric
df['Speed Limit[km/h]'] = pd.to_numeric(df['Speed Limit[km/h]'], errors='coerce')

# Now fill missing values
df['Speed Limit[km/h]'].fillna(df['Speed Limit[km/h]'].median(), inplace=True)

# This column is already numeric, just fill
df['Speed Limit with Direction[km/h]'].fillna(
    df['Speed Limit with Direction[km/h]'].median(), inplace=True
)

/tmp/ipython-input-3617029715.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Speed Limit[km/h]'].fillna(df['Speed Limit[km/h]'].median(), inplace=True)
/tmp/ipython-input-3617029715.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Speed Limit with Direction[km/h]'].fillna(

In [ ]:
print(df['Speed Limit[km/h]'].dtype)
print(df['Speed Limit with Direction[km/h]'].isnull().sum())

float64
0

In [ ]:
df.isnull().sum().sort_values(ascending=False)

Air Conditioning Power[kW]          20000
Fuel Rate[L/hr]                     20000
Bus Stops                           19583
Focus Points                        19432
Intersection                        19156
Long Term Fuel Trim Bank 2[%]       17872
Short Term Fuel Trim Bank 2[%]      16927
Heater Power[Watts]                 13602
HV Battery SOC[%]                   12710
HV Battery Current[A]               12710
HV Battery Voltage[V]               12710
Air Conditioning Power[Watts]       12710
OAT[DegC]                           11553
Absolute Load[%]                     9877
Long Term Fuel Trim Bank 1[%]        7793
Short Term Fuel Trim Bank 1[%]       6848
MAF[g/sec]                           6604
Engine RPM[RPM]                      6398
Energy_Consumption                    709
Gradient                              444
Class of Speed Limit                  362
DayNum                                  0
VehId                                   0
Trip                                    0
Longitude[deg]                          0
Latitude[deg]                           0
Timestamp(ms)                           0
Vehicle Speed[km/h]                     0
Matchted Latitude[deg]                  0
Elevation Raw[m]                        0
Elevation Smoothed[m]                   0
Speed Limit[km/h]                       0
Match Type                              0
Matched Longitude[deg]                  0
Speed Limit with Direction[km/h]        0
dtype: int64

In [ ]:
target = 'Energy_Consumption'

threshold = 0.7 * len(df)

high_missing_cols = df.isnull().sum()[
    (df.isnull().sum() > threshold) & (df.columns != target)
].index

df.drop(columns=high_missing_cols, inplace=True)

print("Dropped Columns:", list(high_missing_cols))
print("Target still present:", target in df.columns)

Dropped Columns: ['Fuel Rate[L/hr]', 'Air Conditioning Power[kW]', 'Short Term Fuel Trim Bank 2[%]', 'Long Term Fuel Trim Bank 2[%]', 'Intersection', 'Bus Stops', 'Focus Points']
Target still present: True

In [ ]:
# Step 2: Interpolate medium-missing time-series features
medium_missing_cols = [
    'Energy_Consumption',
    'Absolute Load[%]',
    'MAF[g/sec]'
]

for col in medium_missing_cols:
    if col in df.columns:
        df[col] = df[col].interpolate(method='linear')

In [ ]:
# Step 3: Handle low-missing values
df['Gradient'] = df['Gradient'].interpolate(method='linear')
df['Engine RPM[RPM]'] = df['Engine RPM[RPM]'].interpolate(method='linear')
df['Vehicle Speed[km/h]'] = df['Vehicle Speed[km/h]'].interpolate(method='linear')

# Categorical → fill with mode
df['Class of Speed Limit'].fillna(df['Class of Speed Limit'].mode()[0], inplace=True)

/tmp/ipython-input-208176911.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Class of Speed Limit'].fillna(df['Class of Speed Limit'].mode()[0], inplace=True)

In [ ]:
# Fill any remaining numeric NaNs with median
num_cols = df.select_dtypes(include=['float64', 'int64']).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

print("Remaining Missing Values:\n", df.isnull().sum().sum())

Remaining Missing Values:
 0

In [ ]:
df.isnull().sum().sort_values(ascending=False)

DayNum                              0
VehId                               0
Trip                                0
Timestamp(ms)                       0
Latitude[deg]                       0
Longitude[deg]                      0
Vehicle Speed[km/h]                 0
MAF[g/sec]                          0
Engine RPM[RPM]                     0
Absolute Load[%]                    0
OAT[DegC]                           0
Air Conditioning Power[Watts]       0
Heater Power[Watts]                 0
HV Battery Current[A]               0
HV Battery SOC[%]                   0
HV Battery Voltage[V]               0
Short Term Fuel Trim Bank 1[%]      0
Long Term Fuel Trim Bank 1[%]       0
Elevation Raw[m]                    0
Elevation Smoothed[m]               0
Gradient                            0
Energy_Consumption                  0
Matchted Latitude[deg]              0
Matched Longitude[deg]              0
Match Type                          0
Class of Speed Limit                0
Speed Limit[km/h]                   0
Speed Limit with Direction[km/h]    0
dtype: int64

In [ ]:
# If Timestamp exists, use it
if 'Timestamp(ms)' in df.columns:
    df['Timestamp'] = pd.to_datetime(df['Timestamp(ms)'], unit='ms')
    df['Hour'] = df['Timestamp'].dt.hour
    df['Day'] = df['Timestamp'].dt.day

In [ ]:
df['Speed_x_RPM'] = df['Vehicle Speed[km/h]'] * df['Engine RPM[RPM]']
df['Elevation_Change'] = df['Elevation Smoothed[m]'].diff().fillna(0)

ENCODE

In [ ]:
le = LabelEncoder()

if 'Class of Speed Limit' in df.columns:
    df['Class of Speed Limit'] = le.fit_transform(df['Class of Speed Limit'])

if 'Match Type' in df.columns:
    df['Match Type'] = le.fit_transform(df['Match Type'])

In [ ]:
#drop leaking colmns
drop_cols = [
    'VehId', 'Trip',
    'Matchted Latitude[deg]', 'Matched Longitude[deg]',
    'Timestamp(ms)', 'Timestamp'
]
df = df.drop(columns=drop_cols, errors='ignore')

# Remove invalid/zero/negative energy values
df = df[df['Energy_Consumption'] > 0]

# Clip extreme outliers (1% to 99%)
q_low = df['Energy_Consumption'].quantile(0.01)
q_high = df['Energy_Consumption'].quantile(0.99)
df['Energy_Consumption'] = df['Energy_Consumption'].clip(q_low, q_high)

# Log transform target to stabilize tiny values
df['Energy_Consumption'] = np.log1p(df['Energy_Consumption'])


X = df.drop(columns=['Energy_Consumption'])
y = df['Energy_Consumption']

In [ ]:
print('Energy_Consumption' in df.columns)
print(df.columns.tolist())

True
['DayNum', 'Latitude[deg]', 'Longitude[deg]', 'Vehicle Speed[km/h]', 'MAF[g/sec]', 'Engine RPM[RPM]', 'Absolute Load[%]', 'OAT[DegC]', 'Air Conditioning Power[Watts]', 'Heater Power[Watts]', 'HV Battery Current[A]', 'HV Battery SOC[%]', 'HV Battery Voltage[V]', 'Short Term Fuel Trim Bank 1[%]', 'Long Term Fuel Trim Bank 1[%]', 'Elevation Raw[m]', 'Elevation Smoothed[m]', 'Gradient', 'Energy_Consumption', 'Match Type', 'Class of Speed Limit', 'Speed Limit[km/h]', 'Speed Limit with Direction[km/h]', 'Hour', 'Day', 'Speed_x_RPM', 'Elevation_Change']

In [ ]:
target = 'Energy_Consumption'

X = df.drop(columns=[target])
y = df[target]

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

Feature shape: (16598, 26)
Target shape: (16598,)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=False
)

In [ ]:
# model = RandomForestRegressor(n_estimators=100, random_state=42)
model = RandomForestRegressor(
    n_estimators=300,
    max_depth=15,
    random_state=42,
    n_jobs=-1
)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

MAE: 0.0005646673154754906
R2 Score: 0.7241684461563348

In [ ]:
print("Target stats:")
print(y.describe())
print("\nZero values:", (y == 0).sum())
print("Unique values:", y.nunique())

Target stats:
count    16598.000000
mean         0.003441
std          0.003378
min          0.000054
25%          0.000875
50%          0.002437
75%          0.004863
max          0.016330
Name: Energy_Consumption, dtype: float64

Zero values: 0
Unique values: 9840